name: CI
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: setup
        uses: ./.github/workflows/composite/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run test
        run: make test

  code_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: setup
        uses: ./.github/workflows/composite/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run ruff check
        run: make ruff-check

      - name: Run black check
        run: make black-check

  type_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: setup
        uses: ./.github/workflows/composite/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run mypy
        run: make mypy

  docker_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in Dockerfile
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'Dockerfile'

      - name: Lint Dockerfile
        if: steps.filter.outputs.changed == 'true'
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
